### PR TITLE
Laravel 10 support

### PR DESCRIPTION
**Pull request by blakekrone**
Added support for Illuminate/Support 10

### CODE REVIEW

**Comment by Rich2k** [comment]
I'm afraid I can't merge this, you've changed the license header, the name spaces, etc

**Comment by Rich2k** [comment]
Whilst you can publish on packagist as it's MIT licensed, why have you rather than keep the singular package? However you have removed my Copyright from your license file which IS a breach of the MIT license

**Comment by blakekrone** [comment]
Wasn’t sure you were still supporting this package or not. So I had to repackage to move forward with an app. If this is still going to be supported then I have no issues pushing prs here. On Jan 12, 2024, at 1:11 PM, Richard Hyland ***@***.***> wrote:﻿
Whilst you can publish on packagist as it's MIT licensed, why have you rather than keep the singular package?

**Comment by Rich2k** [comment]
Indeed it is, we did have Christmas in the middle there!

**Pull request closed without merging**
